// Code generated by "go run ./gen". DO NOT EDIT.

package chalk

import "github.com/chalk/chalk-go/ansistyles"

// mustStyle resolves a style that the generator proved exists.
func mustStyle(name string) ansistyles.Style {
	style, ok := ansistyles.Lookup(name)
	if !ok {
		panic("chalk: missing style " + name)
	}

	return style
}

// Resolved table entries, bound once at start-up.
var (
	styleReset                  = mustStyle("reset")
	styleBold                   = mustStyle("bold")
	styleDim                    = mustStyle("dim")
	styleItalic                 = mustStyle("italic")
	styleUnderline              = mustStyle("underline")
	styleUnderlineDouble        = mustStyle("underlineDouble")
	styleUnderlineCurly         = mustStyle("underlineCurly")
	styleUnderlineDotted        = mustStyle("underlineDotted")
	styleUnderlineDashed        = mustStyle("underlineDashed")
	styleOverline               = mustStyle("overline")
	styleInverse                = mustStyle("inverse")
	styleHidden                 = mustStyle("hidden")
	styleStrikethrough          = mustStyle("strikethrough")
	styleBlack                  = mustStyle("black")
	styleRed                    = mustStyle("red")
	styleGreen                  = mustStyle("green")
	styleYellow                 = mustStyle("yellow")
	styleBlue                   = mustStyle("blue")
	styleMagenta                = mustStyle("magenta")
	styleCyan                   = mustStyle("cyan")
	styleWhite                  = mustStyle("white")
	styleBlackBright            = mustStyle("blackBright")
	styleGray                   = mustStyle("gray")
	styleGrey                   = mustStyle("grey")
	styleRedBright              = mustStyle("redBright")
	styleGreenBright            = mustStyle("greenBright")
	styleYellowBright           = mustStyle("yellowBright")
	styleBlueBright             = mustStyle("blueBright")
	styleMagentaBright          = mustStyle("magentaBright")
	styleCyanBright             = mustStyle("cyanBright")
	styleWhiteBright            = mustStyle("whiteBright")
	styleBgBlack                = mustStyle("bgBlack")
	styleBgRed                  = mustStyle("bgRed")
	styleBgGreen                = mustStyle("bgGreen")
	styleBgYellow               = mustStyle("bgYellow")
	styleBgBlue                 = mustStyle("bgBlue")
	styleBgMagenta              = mustStyle("bgMagenta")
	styleBgCyan                 = mustStyle("bgCyan")
	styleBgWhite                = mustStyle("bgWhite")
	styleBgBlackBright          = mustStyle("bgBlackBright")
	styleBgGray                 = mustStyle("bgGray")
	styleBgGrey                 = mustStyle("bgGrey")
	styleBgRedBright            = mustStyle("bgRedBright")
	styleBgGreenBright          = mustStyle("bgGreenBright")
	styleBgYellowBright         = mustStyle("bgYellowBright")
	styleBgBlueBright           = mustStyle("bgBlueBright")
	styleBgMagentaBright        = mustStyle("bgMagentaBright")
	styleBgCyanBright           = mustStyle("bgCyanBright")
	styleBgWhiteBright          = mustStyle("bgWhiteBright")
	styleUnderlineBlack         = mustStyle("underlineBlack")
	styleUnderlineRed           = mustStyle("underlineRed")
	styleUnderlineGreen         = mustStyle("underlineGreen")
	styleUnderlineYellow        = mustStyle("underlineYellow")
	styleUnderlineBlue          = mustStyle("underlineBlue")
	styleUnderlineMagenta       = mustStyle("underlineMagenta")
	styleUnderlineCyan          = mustStyle("underlineCyan")
	styleUnderlineWhite         = mustStyle("underlineWhite")
	styleUnderlineBlackBright   = mustStyle("underlineBlackBright")
	styleUnderlineGray          = mustStyle("underlineGray")
	styleUnderlineGrey          = mustStyle("underlineGrey")
	styleUnderlineRedBright     = mustStyle("underlineRedBright")
	styleUnderlineGreenBright   = mustStyle("underlineGreenBright")
	styleUnderlineYellowBright  = mustStyle("underlineYellowBright")
	styleUnderlineBlueBright    = mustStyle("underlineBlueBright")
	styleUnderlineMagentaBright = mustStyle("underlineMagentaBright")
	styleUnderlineCyanBright    = mustStyle("underlineCyanBright")
	styleUnderlineWhiteBright   = mustStyle("underlineWhiteBright")
)

// Style methods.
// Reset resets all styles.
func (s Style) Reset() Style {
	return s.with(styleReset.Open, styleReset.Close)
}

// Bold renders text in bold, which many terminals show as a brighter color.
func (s Style) Bold() Style {
	return s.with(styleBold.Open, styleBold.Close)
}

// Dim renders text dimmed.
func (s Style) Dim() Style {
	return s.with(styleDim.Open, styleDim.Close)
}

// Italic renders text in italics, which is not widely supported.
func (s Style) Italic() Style {
	return s.with(styleItalic.Open, styleItalic.Close)
}

// Underline underlines text.
func (s Style) Underline() Style {
	return s.with(styleUnderline.Open, styleUnderline.Close)
}

// UnderlineDouble underlines text with a double line.
func (s Style) UnderlineDouble() Style {
	return s.with(styleUnderlineDouble.Open, styleUnderlineDouble.Close)
}

// UnderlineCurly underlines text with a curly line, commonly used to mark errors.
func (s Style) UnderlineCurly() Style {
	return s.with(styleUnderlineCurly.Open, styleUnderlineCurly.Close)
}

// UnderlineDotted underlines text with a dotted line.
func (s Style) UnderlineDotted() Style {
	return s.with(styleUnderlineDotted.Open, styleUnderlineDotted.Close)
}

// UnderlineDashed underlines text with a dashed line.
func (s Style) UnderlineDashed() Style {
	return s.with(styleUnderlineDashed.Open, styleUnderlineDashed.Close)
}

// Overline draws a line above text, which is not widely supported.
func (s Style) Overline() Style {
	return s.with(styleOverline.Open, styleOverline.Close)
}

// Inverse swaps the foreground and background colors.
func (s Style) Inverse() Style {
	return s.with(styleInverse.Open, styleInverse.Close)
}

// Hidden hides text while keeping it selectable, useful for passwords.
func (s Style) Hidden() Style {
	return s.with(styleHidden.Open, styleHidden.Close)
}

// Strikethrough draws a line through text, which is not widely supported.
func (s Style) Strikethrough() Style {
	return s.with(styleStrikethrough.Open, styleStrikethrough.Close)
}

// Black sets the foreground color to black.
func (s Style) Black() Style {
	return s.with(styleBlack.Open, styleBlack.Close)
}

// Red sets the foreground color to red.
func (s Style) Red() Style {
	return s.with(styleRed.Open, styleRed.Close)
}

// Green sets the foreground color to green.
func (s Style) Green() Style {
	return s.with(styleGreen.Open, styleGreen.Close)
}

// Yellow sets the foreground color to yellow.
func (s Style) Yellow() Style {
	return s.with(styleYellow.Open, styleYellow.Close)
}

// Blue sets the foreground color to blue.
func (s Style) Blue() Style {
	return s.with(styleBlue.Open, styleBlue.Close)
}

// Magenta sets the foreground color to magenta.
func (s Style) Magenta() Style {
	return s.with(styleMagenta.Open, styleMagenta.Close)
}

// Cyan sets the foreground color to cyan.
func (s Style) Cyan() Style {
	return s.with(styleCyan.Open, styleCyan.Close)
}

// White sets the foreground color to white.
func (s Style) White() Style {
	return s.with(styleWhite.Open, styleWhite.Close)
}

// BlackBright sets the foreground color to bright black.
func (s Style) BlackBright() Style {
	return s.with(styleBlackBright.Open, styleBlackBright.Close)
}

// Gray sets the foreground color to gray.
//
// It is an alias of BlackBright.
func (s Style) Gray() Style {
	return s.with(styleGray.Open, styleGray.Close)
}

// Grey sets the foreground color to grey.
//
// It is an alias of BlackBright.
func (s Style) Grey() Style {
	return s.with(styleGrey.Open, styleGrey.Close)
}

// RedBright sets the foreground color to bright red.
func (s Style) RedBright() Style {
	return s.with(styleRedBright.Open, styleRedBright.Close)
}

// GreenBright sets the foreground color to bright green.
func (s Style) GreenBright() Style {
	return s.with(styleGreenBright.Open, styleGreenBright.Close)
}

// YellowBright sets the foreground color to bright yellow.
func (s Style) YellowBright() Style {
	return s.with(styleYellowBright.Open, styleYellowBright.Close)
}

// BlueBright sets the foreground color to bright blue.
func (s Style) BlueBright() Style {
	return s.with(styleBlueBright.Open, styleBlueBright.Close)
}

// MagentaBright sets the foreground color to bright magenta.
func (s Style) MagentaBright() Style {
	return s.with(styleMagentaBright.Open, styleMagentaBright.Close)
}

// CyanBright sets the foreground color to bright cyan.
func (s Style) CyanBright() Style {
	return s.with(styleCyanBright.Open, styleCyanBright.Close)
}

// WhiteBright sets the foreground color to bright white.
func (s Style) WhiteBright() Style {
	return s.with(styleWhiteBright.Open, styleWhiteBright.Close)
}

// BgBlack sets the background color to black.
func (s Style) BgBlack() Style {
	return s.with(styleBgBlack.Open, styleBgBlack.Close)
}

// BgRed sets the background color to red.
func (s Style) BgRed() Style {
	return s.with(styleBgRed.Open, styleBgRed.Close)
}

// BgGreen sets the background color to green.
func (s Style) BgGreen() Style {
	return s.with(styleBgGreen.Open, styleBgGreen.Close)
}

// BgYellow sets the background color to yellow.
func (s Style) BgYellow() Style {
	return s.with(styleBgYellow.Open, styleBgYellow.Close)
}

// BgBlue sets the background color to blue.
func (s Style) BgBlue() Style {
	return s.with(styleBgBlue.Open, styleBgBlue.Close)
}

// BgMagenta sets the background color to magenta.
func (s Style) BgMagenta() Style {
	return s.with(styleBgMagenta.Open, styleBgMagenta.Close)
}

// BgCyan sets the background color to cyan.
func (s Style) BgCyan() Style {
	return s.with(styleBgCyan.Open, styleBgCyan.Close)
}

// BgWhite sets the background color to white.
func (s Style) BgWhite() Style {
	return s.with(styleBgWhite.Open, styleBgWhite.Close)
}

// BgBlackBright sets the background color to bright black.
func (s Style) BgBlackBright() Style {
	return s.with(styleBgBlackBright.Open, styleBgBlackBright.Close)
}

// BgGray sets the background color to gray.
//
// It is an alias of BgBlackBright.
func (s Style) BgGray() Style {
	return s.with(styleBgGray.Open, styleBgGray.Close)
}

// BgGrey sets the background color to grey.
//
// It is an alias of BgBlackBright.
func (s Style) BgGrey() Style {
	return s.with(styleBgGrey.Open, styleBgGrey.Close)
}

// BgRedBright sets the background color to bright red.
func (s Style) BgRedBright() Style {
	return s.with(styleBgRedBright.Open, styleBgRedBright.Close)
}

// BgGreenBright sets the background color to bright green.
func (s Style) BgGreenBright() Style {
	return s.with(styleBgGreenBright.Open, styleBgGreenBright.Close)
}

// BgYellowBright sets the background color to bright yellow.
func (s Style) BgYellowBright() Style {
	return s.with(styleBgYellowBright.Open, styleBgYellowBright.Close)
}

// BgBlueBright sets the background color to bright blue.
func (s Style) BgBlueBright() Style {
	return s.with(styleBgBlueBright.Open, styleBgBlueBright.Close)
}

// BgMagentaBright sets the background color to bright magenta.
func (s Style) BgMagentaBright() Style {
	return s.with(styleBgMagentaBright.Open, styleBgMagentaBright.Close)
}

// BgCyanBright sets the background color to bright cyan.
func (s Style) BgCyanBright() Style {
	return s.with(styleBgCyanBright.Open, styleBgCyanBright.Close)
}

// BgWhiteBright sets the background color to bright white.
func (s Style) BgWhiteBright() Style {
	return s.with(styleBgWhiteBright.Open, styleBgWhiteBright.Close)
}

// UnderlineBlack sets the underline color to black.
func (s Style) UnderlineBlack() Style {
	return s.with(styleUnderlineBlack.Open, styleUnderlineBlack.Close)
}

// UnderlineRed sets the underline color to red.
func (s Style) UnderlineRed() Style {
	return s.with(styleUnderlineRed.Open, styleUnderlineRed.Close)
}

// UnderlineGreen sets the underline color to green.
func (s Style) UnderlineGreen() Style {
	return s.with(styleUnderlineGreen.Open, styleUnderlineGreen.Close)
}

// UnderlineYellow sets the underline color to yellow.
func (s Style) UnderlineYellow() Style {
	return s.with(styleUnderlineYellow.Open, styleUnderlineYellow.Close)
}

// UnderlineBlue sets the underline color to blue.
func (s Style) UnderlineBlue() Style {
	return s.with(styleUnderlineBlue.Open, styleUnderlineBlue.Close)
}

// UnderlineMagenta sets the underline color to magenta.
func (s Style) UnderlineMagenta() Style {
	return s.with(styleUnderlineMagenta.Open, styleUnderlineMagenta.Close)
}

// UnderlineCyan sets the underline color to cyan.
func (s Style) UnderlineCyan() Style {
	return s.with(styleUnderlineCyan.Open, styleUnderlineCyan.Close)
}

// UnderlineWhite sets the underline color to white.
func (s Style) UnderlineWhite() Style {
	return s.with(styleUnderlineWhite.Open, styleUnderlineWhite.Close)
}

// UnderlineBlackBright sets the underline color to bright black.
func (s Style) UnderlineBlackBright() Style {
	return s.with(styleUnderlineBlackBright.Open, styleUnderlineBlackBright.Close)
}

// UnderlineGray sets the underline color to gray.
//
// It is an alias of UnderlineBlackBright.
func (s Style) UnderlineGray() Style {
	return s.with(styleUnderlineGray.Open, styleUnderlineGray.Close)
}

// UnderlineGrey sets the underline color to grey.
//
// It is an alias of UnderlineBlackBright.
func (s Style) UnderlineGrey() Style {
	return s.with(styleUnderlineGrey.Open, styleUnderlineGrey.Close)
}

// UnderlineRedBright sets the underline color to bright red.
func (s Style) UnderlineRedBright() Style {
	return s.with(styleUnderlineRedBright.Open, styleUnderlineRedBright.Close)
}

// UnderlineGreenBright sets the underline color to bright green.
func (s Style) UnderlineGreenBright() Style {
	return s.with(styleUnderlineGreenBright.Open, styleUnderlineGreenBright.Close)
}

// UnderlineYellowBright sets the underline color to bright yellow.
func (s Style) UnderlineYellowBright() Style {
	return s.with(styleUnderlineYellowBright.Open, styleUnderlineYellowBright.Close)
}

// UnderlineBlueBright sets the underline color to bright blue.
func (s Style) UnderlineBlueBright() Style {
	return s.with(styleUnderlineBlueBright.Open, styleUnderlineBlueBright.Close)
}

// UnderlineMagentaBright sets the underline color to bright magenta.
func (s Style) UnderlineMagentaBright() Style {
	return s.with(styleUnderlineMagentaBright.Open, styleUnderlineMagentaBright.Close)
}

// UnderlineCyanBright sets the underline color to bright cyan.
func (s Style) UnderlineCyanBright() Style {
	return s.with(styleUnderlineCyanBright.Open, styleUnderlineCyanBright.Close)
}

// UnderlineWhiteBright sets the underline color to bright white.
func (s Style) UnderlineWhiteBright() Style {
	return s.with(styleUnderlineWhiteBright.Open, styleUnderlineWhiteBright.Close)
}

// Instance methods. Each starts a chain bound to the instance.

// Reset starts a chain that resets all styles.
func (i *Instance) Reset() Style {
	return i.Root().Reset()
}

// Bold starts a chain that renders text in bold, which many terminals show as a brighter color.
func (i *Instance) Bold() Style {
	return i.Root().Bold()
}

// Dim starts a chain that renders text dimmed.
func (i *Instance) Dim() Style {
	return i.Root().Dim()
}

// Italic starts a chain that renders text in italics, which is not widely supported.
func (i *Instance) Italic() Style {
	return i.Root().Italic()
}

// Underline starts a chain that underlines text.
func (i *Instance) Underline() Style {
	return i.Root().Underline()
}

// UnderlineDouble starts a chain that underlines text with a double line.
func (i *Instance) UnderlineDouble() Style {
	return i.Root().UnderlineDouble()
}

// UnderlineCurly starts a chain that underlines text with a curly line, commonly used to mark errors.
func (i *Instance) UnderlineCurly() Style {
	return i.Root().UnderlineCurly()
}

// UnderlineDotted starts a chain that underlines text with a dotted line.
func (i *Instance) UnderlineDotted() Style {
	return i.Root().UnderlineDotted()
}

// UnderlineDashed starts a chain that underlines text with a dashed line.
func (i *Instance) UnderlineDashed() Style {
	return i.Root().UnderlineDashed()
}

// Overline starts a chain that draws a line above text, which is not widely supported.
func (i *Instance) Overline() Style {
	return i.Root().Overline()
}

// Inverse starts a chain that swaps the foreground and background colors.
func (i *Instance) Inverse() Style {
	return i.Root().Inverse()
}

// Hidden starts a chain that hides text while keeping it selectable, useful for passwords.
func (i *Instance) Hidden() Style {
	return i.Root().Hidden()
}

// Strikethrough starts a chain that draws a line through text, which is not widely supported.
func (i *Instance) Strikethrough() Style {
	return i.Root().Strikethrough()
}

// Black starts a chain that sets the foreground color to black.
func (i *Instance) Black() Style {
	return i.Root().Black()
}

// Red starts a chain that sets the foreground color to red.
func (i *Instance) Red() Style {
	return i.Root().Red()
}

// Green starts a chain that sets the foreground color to green.
func (i *Instance) Green() Style {
	return i.Root().Green()
}

// Yellow starts a chain that sets the foreground color to yellow.
func (i *Instance) Yellow() Style {
	return i.Root().Yellow()
}

// Blue starts a chain that sets the foreground color to blue.
func (i *Instance) Blue() Style {
	return i.Root().Blue()
}

// Magenta starts a chain that sets the foreground color to magenta.
func (i *Instance) Magenta() Style {
	return i.Root().Magenta()
}

// Cyan starts a chain that sets the foreground color to cyan.
func (i *Instance) Cyan() Style {
	return i.Root().Cyan()
}

// White starts a chain that sets the foreground color to white.
func (i *Instance) White() Style {
	return i.Root().White()
}

// BlackBright starts a chain that sets the foreground color to bright black.
func (i *Instance) BlackBright() Style {
	return i.Root().BlackBright()
}

// Gray starts a chain that sets the foreground color to gray.
func (i *Instance) Gray() Style {
	return i.Root().Gray()
}

// Grey starts a chain that sets the foreground color to grey.
func (i *Instance) Grey() Style {
	return i.Root().Grey()
}

// RedBright starts a chain that sets the foreground color to bright red.
func (i *Instance) RedBright() Style {
	return i.Root().RedBright()
}

// GreenBright starts a chain that sets the foreground color to bright green.
func (i *Instance) GreenBright() Style {
	return i.Root().GreenBright()
}

// YellowBright starts a chain that sets the foreground color to bright yellow.
func (i *Instance) YellowBright() Style {
	return i.Root().YellowBright()
}

// BlueBright starts a chain that sets the foreground color to bright blue.
func (i *Instance) BlueBright() Style {
	return i.Root().BlueBright()
}

// MagentaBright starts a chain that sets the foreground color to bright magenta.
func (i *Instance) MagentaBright() Style {
	return i.Root().MagentaBright()
}

// CyanBright starts a chain that sets the foreground color to bright cyan.
func (i *Instance) CyanBright() Style {
	return i.Root().CyanBright()
}

// WhiteBright starts a chain that sets the foreground color to bright white.
func (i *Instance) WhiteBright() Style {
	return i.Root().WhiteBright()
}

// BgBlack starts a chain that sets the background color to black.
func (i *Instance) BgBlack() Style {
	return i.Root().BgBlack()
}

// BgRed starts a chain that sets the background color to red.
func (i *Instance) BgRed() Style {
	return i.Root().BgRed()
}

// BgGreen starts a chain that sets the background color to green.
func (i *Instance) BgGreen() Style {
	return i.Root().BgGreen()
}

// BgYellow starts a chain that sets the background color to yellow.
func (i *Instance) BgYellow() Style {
	return i.Root().BgYellow()
}

// BgBlue starts a chain that sets the background color to blue.
func (i *Instance) BgBlue() Style {
	return i.Root().BgBlue()
}

// BgMagenta starts a chain that sets the background color to magenta.
func (i *Instance) BgMagenta() Style {
	return i.Root().BgMagenta()
}

// BgCyan starts a chain that sets the background color to cyan.
func (i *Instance) BgCyan() Style {
	return i.Root().BgCyan()
}

// BgWhite starts a chain that sets the background color to white.
func (i *Instance) BgWhite() Style {
	return i.Root().BgWhite()
}

// BgBlackBright starts a chain that sets the background color to bright black.
func (i *Instance) BgBlackBright() Style {
	return i.Root().BgBlackBright()
}

// BgGray starts a chain that sets the background color to gray.
func (i *Instance) BgGray() Style {
	return i.Root().BgGray()
}

// BgGrey starts a chain that sets the background color to grey.
func (i *Instance) BgGrey() Style {
	return i.Root().BgGrey()
}

// BgRedBright starts a chain that sets the background color to bright red.
func (i *Instance) BgRedBright() Style {
	return i.Root().BgRedBright()
}

// BgGreenBright starts a chain that sets the background color to bright green.
func (i *Instance) BgGreenBright() Style {
	return i.Root().BgGreenBright()
}

// BgYellowBright starts a chain that sets the background color to bright yellow.
func (i *Instance) BgYellowBright() Style {
	return i.Root().BgYellowBright()
}

// BgBlueBright starts a chain that sets the background color to bright blue.
func (i *Instance) BgBlueBright() Style {
	return i.Root().BgBlueBright()
}

// BgMagentaBright starts a chain that sets the background color to bright magenta.
func (i *Instance) BgMagentaBright() Style {
	return i.Root().BgMagentaBright()
}

// BgCyanBright starts a chain that sets the background color to bright cyan.
func (i *Instance) BgCyanBright() Style {
	return i.Root().BgCyanBright()
}

// BgWhiteBright starts a chain that sets the background color to bright white.
func (i *Instance) BgWhiteBright() Style {
	return i.Root().BgWhiteBright()
}

// UnderlineBlack starts a chain that sets the underline color to black.
func (i *Instance) UnderlineBlack() Style {
	return i.Root().UnderlineBlack()
}

// UnderlineRed starts a chain that sets the underline color to red.
func (i *Instance) UnderlineRed() Style {
	return i.Root().UnderlineRed()
}

// UnderlineGreen starts a chain that sets the underline color to green.
func (i *Instance) UnderlineGreen() Style {
	return i.Root().UnderlineGreen()
}

// UnderlineYellow starts a chain that sets the underline color to yellow.
func (i *Instance) UnderlineYellow() Style {
	return i.Root().UnderlineYellow()
}

// UnderlineBlue starts a chain that sets the underline color to blue.
func (i *Instance) UnderlineBlue() Style {
	return i.Root().UnderlineBlue()
}

// UnderlineMagenta starts a chain that sets the underline color to magenta.
func (i *Instance) UnderlineMagenta() Style {
	return i.Root().UnderlineMagenta()
}

// UnderlineCyan starts a chain that sets the underline color to cyan.
func (i *Instance) UnderlineCyan() Style {
	return i.Root().UnderlineCyan()
}

// UnderlineWhite starts a chain that sets the underline color to white.
func (i *Instance) UnderlineWhite() Style {
	return i.Root().UnderlineWhite()
}

// UnderlineBlackBright starts a chain that sets the underline color to bright black.
func (i *Instance) UnderlineBlackBright() Style {
	return i.Root().UnderlineBlackBright()
}

// UnderlineGray starts a chain that sets the underline color to gray.
func (i *Instance) UnderlineGray() Style {
	return i.Root().UnderlineGray()
}

// UnderlineGrey starts a chain that sets the underline color to grey.
func (i *Instance) UnderlineGrey() Style {
	return i.Root().UnderlineGrey()
}

// UnderlineRedBright starts a chain that sets the underline color to bright red.
func (i *Instance) UnderlineRedBright() Style {
	return i.Root().UnderlineRedBright()
}

// UnderlineGreenBright starts a chain that sets the underline color to bright green.
func (i *Instance) UnderlineGreenBright() Style {
	return i.Root().UnderlineGreenBright()
}

// UnderlineYellowBright starts a chain that sets the underline color to bright yellow.
func (i *Instance) UnderlineYellowBright() Style {
	return i.Root().UnderlineYellowBright()
}

// UnderlineBlueBright starts a chain that sets the underline color to bright blue.
func (i *Instance) UnderlineBlueBright() Style {
	return i.Root().UnderlineBlueBright()
}

// UnderlineMagentaBright starts a chain that sets the underline color to bright magenta.
func (i *Instance) UnderlineMagentaBright() Style {
	return i.Root().UnderlineMagentaBright()
}

// UnderlineCyanBright starts a chain that sets the underline color to bright cyan.
func (i *Instance) UnderlineCyanBright() Style {
	return i.Root().UnderlineCyanBright()
}

// UnderlineWhiteBright starts a chain that sets the underline color to bright white.
func (i *Instance) UnderlineWhiteBright() Style {
	return i.Root().UnderlineWhiteBright()
}

// RGB starts a chain that sets a 24-bit foreground color, downsampling if needed.
func (i *Instance) RGB(r, g, b uint8) Style {
	return i.Root().RGB(r, g, b)
}

// BgRGB starts a chain that sets a 24-bit background color, downsampling if needed.
func (i *Instance) BgRGB(r, g, b uint8) Style {
	return i.Root().BgRGB(r, g, b)
}

// UnderlineRGB starts a chain that sets a 24-bit underline color, downsampling if needed.
func (i *Instance) UnderlineRGB(r, g, b uint8) Style {
	return i.Root().UnderlineRGB(r, g, b)
}

// Hex starts a chain that sets a foreground color from a hex string.
func (i *Instance) Hex(hex string) Style {
	return i.Root().Hex(hex)
}

// BgHex starts a chain that sets a background color from a hex string.
func (i *Instance) BgHex(hex string) Style {
	return i.Root().BgHex(hex)
}

// UnderlineHex starts a chain that sets an underline color from a hex string.
func (i *Instance) UnderlineHex(hex string) Style {
	return i.Root().UnderlineHex(hex)
}

// Ansi256 starts a chain that sets a foreground color from the 256-color palette.
func (i *Instance) Ansi256(code uint8) Style {
	return i.Root().Ansi256(code)
}

// BgAnsi256 starts a chain that sets a background color from the 256-color palette.
func (i *Instance) BgAnsi256(code uint8) Style {
	return i.Root().BgAnsi256(code)
}

// UnderlineAnsi256 starts a chain that sets an underline color from the 256-color palette.
func (i *Instance) UnderlineAnsi256(code uint8) Style {
	return i.Root().UnderlineAnsi256(code)
}

// Visible starts a chain that only renders when colors are enabled.
func (i *Instance) Visible() Style {
	return i.Root().Visible()
}

// By starts a chain with the style registered under an ANSI style name.
func (i *Instance) By(name string) (Style, error) {
	return i.Root().By(name)
}

// Package-level functions. Each starts a chain bound to Default.

// Reset starts a chain that resets all styles.
func Reset() Style {
	return Default.Root().Reset()
}

// Bold starts a chain that renders text in bold, which many terminals show as a brighter color.
func Bold() Style {
	return Default.Root().Bold()
}

// Dim starts a chain that renders text dimmed.
func Dim() Style {
	return Default.Root().Dim()
}

// Italic starts a chain that renders text in italics, which is not widely supported.
func Italic() Style {
	return Default.Root().Italic()
}

// Underline starts a chain that underlines text.
func Underline() Style {
	return Default.Root().Underline()
}

// UnderlineDouble starts a chain that underlines text with a double line.
func UnderlineDouble() Style {
	return Default.Root().UnderlineDouble()
}

// UnderlineCurly starts a chain that underlines text with a curly line, commonly used to mark errors.
func UnderlineCurly() Style {
	return Default.Root().UnderlineCurly()
}

// UnderlineDotted starts a chain that underlines text with a dotted line.
func UnderlineDotted() Style {
	return Default.Root().UnderlineDotted()
}

// UnderlineDashed starts a chain that underlines text with a dashed line.
func UnderlineDashed() Style {
	return Default.Root().UnderlineDashed()
}

// Overline starts a chain that draws a line above text, which is not widely supported.
func Overline() Style {
	return Default.Root().Overline()
}

// Inverse starts a chain that swaps the foreground and background colors.
func Inverse() Style {
	return Default.Root().Inverse()
}

// Hidden starts a chain that hides text while keeping it selectable, useful for passwords.
func Hidden() Style {
	return Default.Root().Hidden()
}

// Strikethrough starts a chain that draws a line through text, which is not widely supported.
func Strikethrough() Style {
	return Default.Root().Strikethrough()
}

// Black starts a chain that sets the foreground color to black.
func Black() Style {
	return Default.Root().Black()
}

// Red starts a chain that sets the foreground color to red.
func Red() Style {
	return Default.Root().Red()
}

// Green starts a chain that sets the foreground color to green.
func Green() Style {
	return Default.Root().Green()
}

// Yellow starts a chain that sets the foreground color to yellow.
func Yellow() Style {
	return Default.Root().Yellow()
}

// Blue starts a chain that sets the foreground color to blue.
func Blue() Style {
	return Default.Root().Blue()
}

// Magenta starts a chain that sets the foreground color to magenta.
func Magenta() Style {
	return Default.Root().Magenta()
}

// Cyan starts a chain that sets the foreground color to cyan.
func Cyan() Style {
	return Default.Root().Cyan()
}

// White starts a chain that sets the foreground color to white.
func White() Style {
	return Default.Root().White()
}

// BlackBright starts a chain that sets the foreground color to bright black.
func BlackBright() Style {
	return Default.Root().BlackBright()
}

// Gray starts a chain that sets the foreground color to gray.
func Gray() Style {
	return Default.Root().Gray()
}

// Grey starts a chain that sets the foreground color to grey.
func Grey() Style {
	return Default.Root().Grey()
}

// RedBright starts a chain that sets the foreground color to bright red.
func RedBright() Style {
	return Default.Root().RedBright()
}

// GreenBright starts a chain that sets the foreground color to bright green.
func GreenBright() Style {
	return Default.Root().GreenBright()
}

// YellowBright starts a chain that sets the foreground color to bright yellow.
func YellowBright() Style {
	return Default.Root().YellowBright()
}

// BlueBright starts a chain that sets the foreground color to bright blue.
func BlueBright() Style {
	return Default.Root().BlueBright()
}

// MagentaBright starts a chain that sets the foreground color to bright magenta.
func MagentaBright() Style {
	return Default.Root().MagentaBright()
}

// CyanBright starts a chain that sets the foreground color to bright cyan.
func CyanBright() Style {
	return Default.Root().CyanBright()
}

// WhiteBright starts a chain that sets the foreground color to bright white.
func WhiteBright() Style {
	return Default.Root().WhiteBright()
}

// BgBlack starts a chain that sets the background color to black.
func BgBlack() Style {
	return Default.Root().BgBlack()
}

// BgRed starts a chain that sets the background color to red.
func BgRed() Style {
	return Default.Root().BgRed()
}

// BgGreen starts a chain that sets the background color to green.
func BgGreen() Style {
	return Default.Root().BgGreen()
}

// BgYellow starts a chain that sets the background color to yellow.
func BgYellow() Style {
	return Default.Root().BgYellow()
}

// BgBlue starts a chain that sets the background color to blue.
func BgBlue() Style {
	return Default.Root().BgBlue()
}

// BgMagenta starts a chain that sets the background color to magenta.
func BgMagenta() Style {
	return Default.Root().BgMagenta()
}

// BgCyan starts a chain that sets the background color to cyan.
func BgCyan() Style {
	return Default.Root().BgCyan()
}

// BgWhite starts a chain that sets the background color to white.
func BgWhite() Style {
	return Default.Root().BgWhite()
}

// BgBlackBright starts a chain that sets the background color to bright black.
func BgBlackBright() Style {
	return Default.Root().BgBlackBright()
}

// BgGray starts a chain that sets the background color to gray.
func BgGray() Style {
	return Default.Root().BgGray()
}

// BgGrey starts a chain that sets the background color to grey.
func BgGrey() Style {
	return Default.Root().BgGrey()
}

// BgRedBright starts a chain that sets the background color to bright red.
func BgRedBright() Style {
	return Default.Root().BgRedBright()
}

// BgGreenBright starts a chain that sets the background color to bright green.
func BgGreenBright() Style {
	return Default.Root().BgGreenBright()
}

// BgYellowBright starts a chain that sets the background color to bright yellow.
func BgYellowBright() Style {
	return Default.Root().BgYellowBright()
}

// BgBlueBright starts a chain that sets the background color to bright blue.
func BgBlueBright() Style {
	return Default.Root().BgBlueBright()
}

// BgMagentaBright starts a chain that sets the background color to bright magenta.
func BgMagentaBright() Style {
	return Default.Root().BgMagentaBright()
}

// BgCyanBright starts a chain that sets the background color to bright cyan.
func BgCyanBright() Style {
	return Default.Root().BgCyanBright()
}

// BgWhiteBright starts a chain that sets the background color to bright white.
func BgWhiteBright() Style {
	return Default.Root().BgWhiteBright()
}

// UnderlineBlack starts a chain that sets the underline color to black.
func UnderlineBlack() Style {
	return Default.Root().UnderlineBlack()
}

// UnderlineRed starts a chain that sets the underline color to red.
func UnderlineRed() Style {
	return Default.Root().UnderlineRed()
}

// UnderlineGreen starts a chain that sets the underline color to green.
func UnderlineGreen() Style {
	return Default.Root().UnderlineGreen()
}

// UnderlineYellow starts a chain that sets the underline color to yellow.
func UnderlineYellow() Style {
	return Default.Root().UnderlineYellow()
}

// UnderlineBlue starts a chain that sets the underline color to blue.
func UnderlineBlue() Style {
	return Default.Root().UnderlineBlue()
}

// UnderlineMagenta starts a chain that sets the underline color to magenta.
func UnderlineMagenta() Style {
	return Default.Root().UnderlineMagenta()
}

// UnderlineCyan starts a chain that sets the underline color to cyan.
func UnderlineCyan() Style {
	return Default.Root().UnderlineCyan()
}

// UnderlineWhite starts a chain that sets the underline color to white.
func UnderlineWhite() Style {
	return Default.Root().UnderlineWhite()
}

// UnderlineBlackBright starts a chain that sets the underline color to bright black.
func UnderlineBlackBright() Style {
	return Default.Root().UnderlineBlackBright()
}

// UnderlineGray starts a chain that sets the underline color to gray.
func UnderlineGray() Style {
	return Default.Root().UnderlineGray()
}

// UnderlineGrey starts a chain that sets the underline color to grey.
func UnderlineGrey() Style {
	return Default.Root().UnderlineGrey()
}

// UnderlineRedBright starts a chain that sets the underline color to bright red.
func UnderlineRedBright() Style {
	return Default.Root().UnderlineRedBright()
}

// UnderlineGreenBright starts a chain that sets the underline color to bright green.
func UnderlineGreenBright() Style {
	return Default.Root().UnderlineGreenBright()
}

// UnderlineYellowBright starts a chain that sets the underline color to bright yellow.
func UnderlineYellowBright() Style {
	return Default.Root().UnderlineYellowBright()
}

// UnderlineBlueBright starts a chain that sets the underline color to bright blue.
func UnderlineBlueBright() Style {
	return Default.Root().UnderlineBlueBright()
}

// UnderlineMagentaBright starts a chain that sets the underline color to bright magenta.
func UnderlineMagentaBright() Style {
	return Default.Root().UnderlineMagentaBright()
}

// UnderlineCyanBright starts a chain that sets the underline color to bright cyan.
func UnderlineCyanBright() Style {
	return Default.Root().UnderlineCyanBright()
}

// UnderlineWhiteBright starts a chain that sets the underline color to bright white.
func UnderlineWhiteBright() Style {
	return Default.Root().UnderlineWhiteBright()
}

// RGB starts a chain that sets a 24-bit foreground color, downsampling if needed.
func RGB(r, g, b uint8) Style {
	return Default.Root().RGB(r, g, b)
}

// BgRGB starts a chain that sets a 24-bit background color, downsampling if needed.
func BgRGB(r, g, b uint8) Style {
	return Default.Root().BgRGB(r, g, b)
}

// UnderlineRGB starts a chain that sets a 24-bit underline color, downsampling if needed.
func UnderlineRGB(r, g, b uint8) Style {
	return Default.Root().UnderlineRGB(r, g, b)
}

// Hex starts a chain that sets a foreground color from a hex string.
func Hex(hex string) Style {
	return Default.Root().Hex(hex)
}

// BgHex starts a chain that sets a background color from a hex string.
func BgHex(hex string) Style {
	return Default.Root().BgHex(hex)
}

// UnderlineHex starts a chain that sets an underline color from a hex string.
func UnderlineHex(hex string) Style {
	return Default.Root().UnderlineHex(hex)
}

// Ansi256 starts a chain that sets a foreground color from the 256-color palette.
func Ansi256(code uint8) Style {
	return Default.Root().Ansi256(code)
}

// BgAnsi256 starts a chain that sets a background color from the 256-color palette.
func BgAnsi256(code uint8) Style {
	return Default.Root().BgAnsi256(code)
}

// UnderlineAnsi256 starts a chain that sets an underline color from the 256-color palette.
func UnderlineAnsi256(code uint8) Style {
	return Default.Root().UnderlineAnsi256(code)
}

// Visible starts a chain that only renders when colors are enabled.
func Visible() Style {
	return Default.Root().Visible()
}

// By starts a chain with the style registered under an ANSI style name.
func By(name string) (Style, error) {
	return Default.Root().By(name)
}
